mutation CreateUser ($firstName: String!, $lastName: String!, $username: String!, $password: String!, $email: Email!) {
  createUser(firstName: $firstName, lastName: $lastName, username: $username, password: $password, email: $email) {
    username
    token
  }
}


mutation LogIn ($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    username
    token
  }
}


mutation CreatePlanMutation (
  $planName: String!, $cycleFrequency: CycleFrequency!, $perCycleCost: Float!, $startDate: String!, $timeZone: TimeZone!) {
  createPlan(planName: $planName, cycleFrequency: $cycleFrequency, perCycleCost: $perCycleCost, startDate: $startDate, timeZone: $timeZone) {
    planId
  }
}


mutation JoinPlan ($planId: PlanID!, $quantity: Int!) {
  joinPlan(planId: $planId, quantity: $quantity) {
    clientSecret
    setupIntentId
    paymentMethods {
      id
      brand
      last4
      expiryMonth
      expiryYear
      default
    }
  }
}


mutation EditPayment {
  editPayment {
    portalSessionURL
  }
}


mutation Unsubscribe ($subscriptionId: SubscriptionID!) {
  unsubscribe(subscriptionId: $subscriptionId) {
    planId
  }
}


mutation UnsubscribeAsPlanOwner($subscriptionId: SubscriptionID!, $newOwner: String!) {
  unsubscribeAsOwner(subscriptionId: $subscriptionId, newOwner: $newOwner) {
    planId
  }
}


mutation EditQuantity($subscriptionId: SubscriptionID!, $newQuantity: Int!) {
  editQuantity(subscriptionId: $subscriptionId, newQuantity: $newQuantity) {
    planId
    quantity
  }
}


mutation DeletePlan($planId: PlanID!) {
  deletePlan(planId: $planId) {
    planId
  }
}


mutation CancelTransaction($setupIntentId: SetupIntentID!) {
  cancelTransaction(setupIntentId: $setupIntentId)
}

mutation SubscribeWithSavedCard($paymentMethodId: PaymentMethodID!, $setupIntentId: SetupIntentID!, $planId: PlanID!, $password: String!) {
  subscribeWithSavedCard(paymentMethodId: $paymentMethodId, setupIntentId: $setupIntentId, planId: $planId, password: $password) {
    planId
    name
    owner {
      firstName
      lastName
      username
    }
    cycleFrequency
    perCycleCost
    activeMembers {
      firstName
      lastName
      username
      quantity
    }
    quantity
    subscriptionId
  }
}
