mutation CreateUser ($firstName: String!, $lastName: String!, $username: String!, $password: String!, $email: String!) {
  createUser(firstName: $firstName, lastName: $lastName, username: $username, password: $password, email: $email) {
    username
    email
    token
  }
}


mutation LogIn ($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    username
    email
    token
  }
}


mutation CreatePlanMutation (
  $planName: String!, $cycleFrequency: CycleFrequency!, $perCycleCost: Float!, $startDate: String!) {
  createPlan(planName: $planName, cycleFrequency: $cycleFrequency, perCycleCost: $perCycleCost, startDate: $startDate) {
    productId
  }
}


mutation JoinPlan ($planId: ID!, $quantity: Int!) {
  joinPlan(planId: $planId, quantity: $quantity) {
    clientSecret
    email
  }
}

mutation EditPayment {
  editPayment {
    portalSessionURL
  }
}

mutation Unsubscribe ($subscriptionId: String!) {
  unsubscribe(subscriptionId: $subscriptionId)
}

mutation UnsubscribeAsPlanOwner($subscriptionId: String!, $planId: String!, $newOwner: String!) {
  unsubscribeAsOwner(subscriptionId: $subscriptionId, planId: $planId, newOwner: $newOwner)
}
