mutation CreateUser ($firstName: String!, $lastName: String!, $username: String!, $password: String!, $email: String!) {
  createUser(firstName: $firstName, lastName: $lastName, username: $username, password: $password, email: $email) {
    username
    email
    token
  }
}


mutation LogIn ($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    username
    email
    token
  }
}


mutation CreatePlanMutation (
  $planName: String!, $cycleFrequency: CycleFrequency!, $perCycleCost: Float!, $startDate: String!, $timeZone: TimeZone!) {
  createPlan(planName: $planName, cycleFrequency: $cycleFrequency, perCycleCost: $perCycleCost, startDate: $startDate, timeZone: $timeZone) {
    planId
  }
}


mutation JoinPlan ($planId: PlanID!, $quantity: Int!) {
  joinPlan(planId: $planId, quantity: $quantity) {
    clientSecret
    subscriptionId
  }
}


mutation EditPayment {
  editPayment {
    portalSessionURL
  }
}


mutation Unsubscribe ($subscriptionId: SubscriptionID!) {
  unsubscribe(subscriptionId: $subscriptionId) {
    planId
  }
}


mutation UnsubscribeAsPlanOwner($subscriptionId: SubscriptionID!, $planId: PlanID!, $newOwner: String!) {
  unsubscribeAsOwner(subscriptionId: $subscriptionId, planId: $planId, newOwner: $newOwner) {
    planId
  }
}


mutation EditQuantity($subscriptionId: SubscriptionID!, $newQuantity: Int!) {
  editQuantity(subscriptionId: $subscriptionId, newQuantity: $newQuantity) {
    planId
    quantity
  }
}


mutation DeletePlan($planId: PlanID!) {
  deletePlan(planId: $planId) {
    planId
  }
}


mutation CancelTransaction($subscriptionId: SubscriptionID!) {
  cancelTransaction(subscriptionId: $subscriptionId) {
    subscriptionId
  }
}
