query ViewOnePlan ($planId: PlanID!) {
  viewOnePlan(planId: $planId) {
    planId
    name
    owner {
      firstName
      lastName
      username
    }
    cycleFrequency
    perCycleCost
    activeMembers {
      firstName
      lastName
      username
      quantity
    }
    quantity
  }
}

query ViewAllPlans {
  viewAllPlans {
    total
    plans {
      planId
      name
      owner {
        firstName
        lastName
      }
      isOwner
      nextBillDate
      cycleFrequency
      perCycleCost
      quantity
      selfCost
    }
  }
}

query RetrieveNotifications {
  retrieveNotifications {
    count
    notifications {
      id
      content
      createdAt
    }
  }
}