query ViewOnePlan ($planId: ID!) {
  viewOnePlan(planId: $planId) {
    name
    owner {
      stripeCusId
      firstName
      lastName
      username
    },
    cycleFrequency
    perCycleCost
    activeMembers {
      stripeCusId
      firstName
      lastName
      username
      quantity
    }
  }
}


query ViewAllPlans {
  viewAllPlans {
    planId
    name
    owner {
      stripeCusId
      firstName
      lastName
      username
    }
    cycleFrequency
    perCycleCost
    activeMembers {
      stripeCusId
      firstName
      lastName
      username
      quantity
    }
  }
}
