query PreJoinPlan ($planId: PlanID!) {
  viewOnePlan(planId: $planId) {
    planId
    name
    cycleFrequency
    perCycleCost
    startDate
    activeMembers {
      firstName
      lastName
      quantity
      joinedDate
      isOwner
    }
    quantity
    owner {
      firstName
      lastName
    }
  }
}


query PlanDetails ($planId: PlanID!) {
  viewOnePlan(planId: $planId) {
    planId
    name
    cycleFrequency
    perCycleCost
    startDate
    owner {
      firstName
      lastName
      username
      fullName @client
    }
    isOwner
    quantity
    selfCost
    totalMembers
    totalQuantity
    subscriptionId
    activeMembers {
      firstName
      lastName
      quantity
      joinedDate
      isOwner
      username
      fullName @client
    }
  }
}


query ViewAllPlans {
  viewAllPlans {
    total
    plans {
      planId
      name
      owner {
        firstName
        lastName
        formattedName @client
      }
      isOwner
      nextBillDate
      cycleFrequency
      perCycleCost
      quantity
      selfCost
    }
  }
}

query RetrieveNotifications {
  retrieveNotifications {
    count
    notifications {
      id
      content
      createdAt
    }
  }
}

query GetEmail {
  getEmail {
    username
    email
  }
}