mutation CreateUser ($firstName: String!, $lastName: String!, $username: String!, $password: String!, $email: String!) {
  createUser(firstName: $firstName, lastName: $lastName, username: $username, password: $password, email: $email) {
    username
    token
  }
}


mutation LogIn ($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    username
    token
  }
}


mutation CreatePlanMutation ($planName: String!, $cycleFrequency: CycleFrequency!, $perCycleCost: Float!, $maxQuantity: Int!) {
  createPlan(planName: $planName, cycleFrequency: $cycleFrequency, perCycleCost: $perCycleCost, maxQuantity: $maxQuantity) {
    productId
  }
}


mutation Pay ($planId: String!, $quantity: Int!) {
  pay(planId: $planId, quantity: $quantity) {
    clientSecret
  }
}
