query ViewOnePlan ($planId: String!) {
  viewOnePlan(planId: $planId) {
    name
    owner {
      firstName
      lastName
      username
    },
    cycleFrequency
    perCycleCost
    maxQuantity
    activeMembers {
      firstName
      lastName
      username
      quantity
    }
  }
}


query ViewAllPlans {
  viewAllPlans {
    planId
    name
    owner {
      firstName
      lastName
      username
    }
    cycleFrequency
    perCycleCost
    activeMembers {
      firstName
      lastName
      username
      quantity
    }
  }
}

# query AllQueries {
#   viewOnePlan(planId: $planId) {
#     name
#     owner {
#       firstName
#       lastName
#       username
#     },
#     cycleFrequency
#     perCycleCost
#     maxQuantity
#     activeMembers {
#       firstName
#       lastName
#       username
#       quantity
#     }
#   }

#   viewAllPlans {
#     planId
#     name
#     owner {
#       firstName
#       lastName
#       username
#     }
#     cycleFrequency
#     perCycleCost
#     activeMembers {
#       firstName
#       lastName
#       username
#       quantity
#     }
#   }
# }